COMMENT ON TABLE osm.railway_point IS 'OpenStreetMap railway points - all points with raailway tag and others defined on https://wiki.openstreetmap.org/wiki/Railways.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/railway.lua';
COMMENT ON TABLE osm.railway_line IS 'OpenStreetMap railway lines - all lines with a railway tag and others defined on https://wiki.openstreetmap.org/wiki/Railways.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/railway.lua';
COMMENT ON TABLE osm.railway_polygon IS 'OpenStreetMap railway polygons - all polygons with a railway tag and others defined on https://wiki.openstreetmap.org/wiki/Railways.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/railway.lua';


ALTER TABLE osm.railway_point
    ADD CONSTRAINT pk_osm_railway_point_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE osm.railway_line
    ADD CONSTRAINT pk_osm_railway_line_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE osm.railway_polygon
    ADD CONSTRAINT pk_osm_railway_polygon_osm_id
    PRIMARY KEY (osm_id)
;


CREATE INDEX ix_osm_railway_point_type ON osm.railway_point (osm_type);
CREATE INDEX ix_osm_railway_line_type ON osm.railway_line (osm_type);
CREATE INDEX ix_osm_railway_polygon_type ON osm.railway_polygon (osm_type);


COMMENT ON COLUMN osm.railway_point.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';
COMMENT ON COLUMN osm.railway_line.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';
COMMENT ON COLUMN osm.railway_polygon.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';

COMMENT ON COLUMN osm.railway_point.geom IS 'Geometry loaded by osm2pgsql.';
COMMENT ON COLUMN osm.railway_line.geom IS 'Geometry loaded by osm2pgsql.';
COMMENT ON COLUMN osm.railway_polygon.geom IS 'Geometry loaded by osm2pgsql.';

COMMENT ON COLUMN osm.railway_point.osm_type IS 'Key indicating type of public transport feature if detail exists, falls back to railway tag. e.g. highway, bus, train, etc';
COMMENT ON COLUMN osm.railway_line.osm_type IS 'Key indicating type of public transport feature if detail exists, falls back to railway tag. e.g. highway, bus, train, etc';
COMMENT ON COLUMN osm.railway_polygon.osm_type IS 'Key indicating type of public transport feature if detail exists, falls back to railway tag. e.g. highway, bus, train, etc';

COMMENT ON COLUMN osm.railway_point.osm_subtype IS 'Value describing osm_type key, e.g. osm_type = "highway", osm_subtype = "bus_stop".';
COMMENT ON COLUMN osm.railway_line.osm_subtype IS 'Value describing osm_type key, e.g. osm_type = "highway", osm_subtype = "bus_stop".';
COMMENT ON COLUMN osm.railway_polygon.osm_subtype IS 'Value describing osm_type key, e.g. osm_type = "highway", osm_subtype = "bus_stop".';

COMMENT ON COLUMN osm.railway_point.railway IS 'Value from railway key, or "other" for additional 1st level keys defined in railway.lua';
COMMENT ON COLUMN osm.railway_line.railway IS 'Value from railway key, or "other" for additional 1st level keys defined in railway.lua';
COMMENT ON COLUMN osm.railway_polygon.railway IS 'Value from railway key, or "other" for additional 1st level keys defined in railway.lua';

COMMENT ON COLUMN osm.railway_point.wheelchair IS 'Indicates if feature is wheelchair accessible. Expected values:  yes, no, limited.  Per https://wiki.openstreetmap.org/wiki/Key:wheelchair';
COMMENT ON COLUMN osm.railway_line.wheelchair IS 'Indicates if feature is wheelchair accessible. Expected values:  yes, no, limited.  Per https://wiki.openstreetmap.org/wiki/Key:wheelchair';
COMMENT ON COLUMN osm.railway_polygon.wheelchair IS 'Indicates if feature is wheelchair accessible. Expected values:  yes, no, limited.  Per https://wiki.openstreetmap.org/wiki/Key:wheelchair';

COMMENT ON COLUMN osm.railway_point.ref IS 'Reference number or code. Best ref option determined by helpers.get_ref(). https://wiki.openstreetmap.org/wiki/Key:ref';
COMMENT ON COLUMN osm.railway_line.ref IS 'Reference number or code. Best ref option determined by helpers.get_ref(). https://wiki.openstreetmap.org/wiki/Key:ref';
COMMENT ON COLUMN osm.railway_polygon.ref IS 'Reference number or code. Best ref option determined by helpers.get_ref(). https://wiki.openstreetmap.org/wiki/Key:ref';

COMMENT ON COLUMN osm.railway_point.layer IS 'Vertical ordering layer (Z) to handle crossing/overlapping features. "All ways without an explicit value are assumed to have layer 0." - per Wiki - https://wiki.openstreetmap.org/wiki/Key:layer';
COMMENT ON COLUMN osm.railway_line.layer IS 'Vertical ordering layer (Z) to handle crossing/overlapping features. "All ways without an explicit value are assumed to have layer 0." - per Wiki - https://wiki.openstreetmap.org/wiki/Key:layer';
COMMENT ON COLUMN osm.railway_polygon.layer IS 'Vertical ordering layer (Z) to handle crossing/overlapping features. "All ways without an explicit value are assumed to have layer 0." - per Wiki - https://wiki.openstreetmap.org/wiki/Key:layer';

COMMENT ON COLUMN osm.railway_point.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';
COMMENT ON COLUMN osm.railway_line.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';
COMMENT ON COLUMN osm.railway_polygon.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';

COMMENT ON COLUMN osm.railway_point.operator IS 'Entity in charge of operations. https://wiki.openstreetmap.org/wiki/Key:operator';
COMMENT ON COLUMN osm.railway_line.operator IS 'Entity in charge of operations. https://wiki.openstreetmap.org/wiki/Key:operator';
COMMENT ON COLUMN osm.railway_polygon.operator IS 'Entity in charge of operations. https://wiki.openstreetmap.org/wiki/Key:operator';

COMMENT ON COLUMN osm.railway_point.network IS 'Route, system or operator. Usage of network key is widely varied. See https://wiki.openstreetmap.org/wiki/Key:network';
COMMENT ON COLUMN osm.railway_line.network IS 'Route, system or operator. Usage of network key is widely varied. See https://wiki.openstreetmap.org/wiki/Key:network';
COMMENT ON COLUMN osm.railway_polygon.network IS 'Route, system or operator. Usage of network key is widely varied. See https://wiki.openstreetmap.org/wiki/Key:network';
